# Generated by Django 5.2 on 2025-04-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('is_running', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=256)),
                ('run_command', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server_files', models.FileField(upload_to='game_servers/')),
            ],
        ),
    ]
